# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py

conda:
  environment: conda_env/devtools/rtd_env.yml

build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-4.10"
